INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (1, '"Children''s Game"');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (2, '"Children''s Game"]');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (3, '''Action / Dexterity''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (4, '''Action / Dexterity'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (5, '''Adventure''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (6, '''Adventure'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (7, '''Age of Reason''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (8, '''American Civil War''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (9, '''American Indian Wars''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (10, '''American Revolutionary War''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (11, '''American West''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (12, '''American West'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (13, '''Ancient''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (14, '''Ancient'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (15, '''Animals''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (16, '''Animals'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (17, '''Arabian''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (18, '''Arabian'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (19, '''Aviation / Flight''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (20, '''Aviation / Flight'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (21, '''Bluffing''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (22, '''Bluffing'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (23, '''Book''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (24, '''Book'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (25, '''Card Game''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (26, '''Card Game'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (27, '''City Building''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (28, '''City Building'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (29, '''Civil War''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (30, '''Civilization''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (31, '''Civilization'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (32, '''Collectible Components''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (33, '''Collectible Components'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (34, '''Comic Book / Strip''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (35, '''Comic Book / Strip'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (36, '''Deduction''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (37, '''Deduction'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (38, '''Dice''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (39, '''Dice'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (40, '''Economic''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (41, '''Economic'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (42, '''Educational''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (43, '''Educational'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (44, '''Electronic''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (45, '''Electronic'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (46, '''Environmental''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (47, '''Environmental'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (48, '''Expansion for Base-game''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (49, '''Expansion for Base-game'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (50, '''Exploration''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (51, '''Exploration'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (52, '''Fan Expansion''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (53, '''Fantasy''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (54, '''Fantasy'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (55, '''Farming''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (56, '''Farming'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (57, '''Fighting''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (58, '''Fighting'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (59, '''Game System''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (60, '''Game System'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (61, '''Horror''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (62, '''Horror'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (63, '''Humor''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (64, '''Humor'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (65, '''Industry / Manufacturing''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (66, '''Industry / Manufacturing'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (67, '''Korean War''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (68, '''Mafia''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (69, '''Mafia'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (70, '''Math''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (71, '''Math'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (72, '''Mature / Adult''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (73, '''Mature / Adult'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (74, '''Maze''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (75, '''Maze'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (76, '''Medical''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (77, '''Medical'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (78, '''Medieval''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (79, '''Medieval'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (80, '''Memory''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (81, '''Memory'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (82, '''Miniatures''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (83, '''Miniatures'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (84, '''Modern Warfare''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (85, '''Modern Warfare'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (86, '''Movies / TV / Radio theme''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (87, '''Movies / TV / Radio theme'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (88, '''Murder/Mystery''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (89, '''Murder/Mystery'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (90, '''Music''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (91, '''Music'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (92, '''Mythology''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (93, '''Mythology'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (94, '''Napoleonic''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (95, '''Napoleonic'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (96, '''Nautical''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (97, '''Nautical'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (98, '''Negotiation''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (99, '''Negotiation'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (100, '''Novel-based''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (101, '''Novel-based'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (102, '''Number''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (103, '''Number'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (104, '''Party Game''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (105, '''Party Game'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (106, '''Pike and Shot''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (107, '''Pike and Shot'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (108, '''Pirates''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (109, '''Pirates'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (110, '''Political''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (111, '''Political'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (112, '''Post-Napoleonic''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (113, '''Post-Napoleonic'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (114, '''Prehistoric''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (115, '''Prehistoric'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (116, '''Print & Play''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (117, '''Print & Play'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (118, '''Puzzle''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (119, '''Puzzle'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (120, '''Racing''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (121, '''Racing'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (122, '''Real-time''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (123, '''Real-time'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (124, '''Religious''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (125, '''Religious'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (126, '''Renaissance''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (127, '''Renaissance'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (128, '''Science Fiction''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (129, '''Science Fiction'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (130, '''Space Exploration''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (131, '''Space Exploration'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (132, '''Spies/Secret Agents''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (133, '''Spies/Secret Agents'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (134, '''Sports''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (135, '''Sports'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (136, '''Territory Building''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (137, '''Territory Building'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (138, '''Trains''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (139, '''Trains'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (140, '''Transportation''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (141, '''Transportation'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (142, '''Travel''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (143, '''Travel'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (144, '''Trivia''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (145, '''Trivia'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (146, '''Video Game Theme''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (147, '''Video Game Theme'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (148, '''Vietnam War''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (149, '''Vietnam War'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (150, '''Wargame''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (151, '''Wargame'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (152, '''Word Game''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (153, '''Word Game'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (154, '''World War I''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (155, '''World War I'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (156, '''World War II''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (157, '''World War II'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (158, '''Zombies'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (159, 'Inconnu');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (160, '["Children''s Game"');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (161, '["Children''s Game"]');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (162, '[''Abstract Strategy''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (163, '[''Abstract Strategy'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (164, '[''Action / Dexterity''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (165, '[''Action / Dexterity'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (166, '[''Adventure''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (167, '[''Adventure'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (168, '[''Age of Reason''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (169, '[''Age of Reason'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (170, '[''American Civil War''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (171, '[''American Civil War'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (172, '[''American Indian Wars''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (173, '[''American Revolutionary War''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (174, '[''American West''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (175, '[''American West'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (176, '[''Ancient''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (177, '[''Ancient'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (178, '[''Animals''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (179, '[''Animals'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (180, '[''Arabian''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (181, '[''Arabian'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (182, '[''Aviation / Flight''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (183, '[''Aviation / Flight'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (184, '[''Bluffing''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (185, '[''Bluffing'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (186, '[''Book''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (187, '[''Book'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (188, '[''Card Game''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (189, '[''Card Game'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (190, '[''City Building''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (191, '[''City Building'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (192, '[''Civil War''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (193, '[''Civil War'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (194, '[''Civilization''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (195, '[''Civilization'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (196, '[''Collectible Components''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (197, '[''Collectible Components'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (198, '[''Comic Book / Strip''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (199, '[''Comic Book / Strip'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (200, '[''Deduction''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (201, '[''Deduction'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (202, '[''Dice''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (203, '[''Dice'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (204, '[''Economic''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (205, '[''Economic'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (206, '[''Educational''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (207, '[''Educational'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (208, '[''Electronic''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (209, '[''Environmental''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (210, '[''Environmental'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (211, '[''Expansion for Base-game''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (212, '[''Exploration''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (213, '[''Exploration'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (214, '[''Fantasy''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (215, '[''Fantasy'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (216, '[''Farming''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (217, '[''Farming'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (218, '[''Fighting''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (219, '[''Fighting'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (220, '[''Horror''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (221, '[''Horror'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (222, '[''Humor''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (223, '[''Humor'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (224, '[''Industry / Manufacturing''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (225, '[''Industry / Manufacturing'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (226, '[''Korean War''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (227, '[''Mafia''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (228, '[''Mafia'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (229, '[''Math''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (230, '[''Math'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (231, '[''Mature / Adult''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (232, '[''Mature / Adult'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (233, '[''Maze''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (234, '[''Maze'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (235, '[''Medical''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (236, '[''Medical'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (237, '[''Medieval''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (238, '[''Medieval'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (239, '[''Memory''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (240, '[''Memory'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (241, '[''Miniatures''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (242, '[''Miniatures'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (243, '[''Modern Warfare''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (244, '[''Modern Warfare'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (245, '[''Movies / TV / Radio theme''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (246, '[''Movies / TV / Radio theme'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (247, '[''Murder/Mystery''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (248, '[''Murder/Mystery'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (249, '[''Music''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (250, '[''Music'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (251, '[''Mythology''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (252, '[''Mythology'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (253, '[''Napoleonic''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (254, '[''Nautical''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (255, '[''Nautical'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (256, '[''Negotiation''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (257, '[''Negotiation'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (258, '[''Novel-based''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (259, '[''Novel-based'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (260, '[''Number''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (261, '[''Number'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (262, '[''Party Game''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (263, '[''Party Game'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (264, '[''Pike and Shot''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (265, '[''Pirates''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (266, '[''Pirates'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (267, '[''Political''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (268, '[''Political'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (269, '[''Post-Napoleonic''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (270, '[''Post-Napoleonic'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (271, '[''Prehistoric''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (272, '[''Prehistoric'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (273, '[''Print & Play''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (274, '[''Print & Play'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (275, '[''Puzzle''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (276, '[''Puzzle'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (277, '[''Racing''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (278, '[''Racing'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (279, '[''Real-time''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (280, '[''Real-time'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (281, '[''Religious''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (282, '[''Religious'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (283, '[''Renaissance''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (284, '[''Renaissance'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (285, '[''Science Fiction''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (286, '[''Science Fiction'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (287, '[''Space Exploration''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (288, '[''Space Exploration'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (289, '[''Spies/Secret Agents''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (290, '[''Spies/Secret Agents'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (291, '[''Sports''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (292, '[''Sports'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (293, '[''Territory Building''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (294, '[''Territory Building'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (295, '[''Trains''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (296, '[''Trains'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (297, '[''Transportation''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (298, '[''Transportation'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (299, '[''Travel''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (300, '[''Travel'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (301, '[''Trivia''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (302, '[''Trivia'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (303, '[''Video Game Theme'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (304, '[''Vietnam War''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (305, '[''Wargame''');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (306, '[''Wargame'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (307, '[''Word Game'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (308, '[''World War II'']');
INSERT INTO CategorieGenre (IDGenre, NomGenre) VALUES (309, '[''Zombies'']');
