INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (1, '"Prisoner''s Dilemma"');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (2, '"Prisoner''s Dilemma"]');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (3, '''Action Points''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (4, '''Action Queue''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (5, '''Action Queue'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (6, '''Action Retrieval''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (7, '''Action Timer''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (8, '''Action/Event''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (9, '''Advantage Token''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (10, '''Alliances''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (11, '''Area Majority / Influence''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (12, '''Area Majority / Influence'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (13, '''Area Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (14, '''Area Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (15, '''Area-Impulse''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (16, '''Area-Impulse'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (17, '''Auction/Bidding''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (18, '''Auction/Bidding'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (19, '''Auction: Dexterity''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (20, '''Auction: Dutch Priority''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (21, '''Auction: Dutch''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (22, '''Auction: English''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (23, '''Auction: Fixed Placement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (24, '''Auction: Once Around''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (25, '''Auction: Sealed Bid''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (26, '''Auction: Sealed Bid'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (27, '''Auction: Turn Order Until Pass''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (28, '''Automatic Resource Growth''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (29, '''Betting and Bluffing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (30, '''Betting and Bluffing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (31, '''Bias''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (32, '''Bias'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (33, '''Bingo''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (34, '''Bribery''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (35, '''Bribery'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (36, '''Campaign / Battle Card Driven''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (37, '''Campaign / Battle Card Driven'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (38, '''Card Drafting''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (39, '''Card Drafting'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (40, '''Card Play Conflict Resolution''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (41, '''Card Play Conflict Resolution'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (42, '''Catch the Leader''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (43, '''Chaining''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (44, '''Chit-Pull System''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (45, '''Chit-Pull System'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (46, '''Closed Economy Auction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (47, '''Command Cards''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (48, '''Commodity Speculation''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (49, '''Commodity Speculation'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (50, '''Communication Limits''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (51, '''Communication Limits'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (52, '''Connections''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (53, '''Constrained Bidding''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (54, '''Constrained Bidding'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (55, '''Contracts''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (56, '''Contracts'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (57, '''Cooperative Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (58, '''Cooperative Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (59, '''Crayon Rail System''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (60, '''Critical Hits and Failures''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (61, '''Cube Tower''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (62, '''Cube Tower'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (63, '''Deck');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (64, '''Deck Construction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (65, '''Deduction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (66, '''Deduction'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (67, '''Delayed Purchase''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (68, '''Delayed Purchase'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (69, '''Dice Rolling''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (70, '''Dice Rolling'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (71, '''Die Icon Resolution''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (72, '''Die Icon Resolution'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (73, '''Different Dice Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (74, '''Drafting''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (75, '''Drafting'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (76, '''Elapsed Real Time Ending''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (77, '''Elapsed Real Time Ending'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (78, '''Enclosure''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (79, '''Enclosure'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (80, '''End Game Bonuses''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (81, '''End Game Bonuses'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (82, '''Events''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (83, '''Events'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (84, '''Finale Ending''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (85, '''Finale Ending'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (86, '''Flicking''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (87, '''Flicking'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (88, '''Follow''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (89, '''Follow'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (90, '''Force Commitment''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (91, '''Grid Coverage''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (92, '''Grid Coverage'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (93, '''Grid Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (94, '''Grid Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (95, '''Hand Management''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (96, '''Hand Management'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (97, '''Hexagon Grid''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (98, '''Hexagon Grid'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (99, '''Hidden Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (100, '''Hidden Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (101, '''Hidden Roles''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (102, '''Hidden Roles'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (103, '''Hidden Victory Points''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (104, '''Hidden Victory Points'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (105, '''Highest-Lowest Scoring''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (106, '''Highest-Lowest Scoring'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (107, '''Hot Potato''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (108, '''Hot Potato'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (109, '''I Cut');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (110, '''Impulse Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (111, '''Income''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (112, '''Income'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (113, '''Increase Value of Unchosen Resources''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (114, '''Increase Value of Unchosen Resources'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (115, '''Induction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (116, '''Interrupts''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (117, '''Interrupts'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (118, '''Investment''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (119, '''Investment'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (120, '''Kill Steal''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (121, '''Kill Steal'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (122, '''King of the Hill''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (123, '''Ladder Climbing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (124, '''Ladder Climbing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (125, '''Layering''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (126, '''Layering'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (127, '''Legacy Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (128, '''Line Drawing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (129, '''Line Drawing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (130, '''Line of Sight''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (131, '''Line of Sight'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (132, '''Loans''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (133, '''Loans'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (134, '''Lose a Turn''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (135, '''Mancala''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (136, '''Map Addition''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (137, '''Map Deformation''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (138, '''Map Reduction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (139, '''Map Reduction'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (140, '''Market''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (141, '''Market'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (142, '''Matching''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (143, '''Matching'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (144, '''Measurement Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (145, '''Measurement Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (146, '''Melding and Splaying''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (147, '''Melding and Splaying'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (148, '''Memory''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (149, '''Memory'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (150, '''Minimap Resolution''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (151, '''Minimap Resolution'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (152, '''Modular Board''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (153, '''Modular Board'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (154, '''Move Through Deck''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (155, '''Move Through Deck'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (156, '''Movement Points''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (157, '''Movement Points'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (158, '''Movement Template''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (159, '''Movement Template'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (160, '''Moving Multiple Units''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (161, '''Multiple Maps''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (162, '''Multiple Maps'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (163, '''Multiple-Lot Auction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (164, '''Multiple-Lot Auction'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (165, '''Narrative Choice / Paragraph''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (166, '''Narrative Choice / Paragraph'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (167, '''Negotiation''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (168, '''Negotiation'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (169, '''Network and Route Building''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (170, '''Network and Route Building'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (171, '''Once-Per-Game Abilities''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (172, '''Once-Per-Game Abilities'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (173, '''Order Counters''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (174, '''Order Counters'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (175, '''Ownership''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (176, '''Ownership'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (177, '''Paper-and-Pencil''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (178, '''Paper-and-Pencil'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (179, '''Passed Action Token''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (180, '''Pattern Building''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (181, '''Pattern Building'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (182, '''Pattern Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (183, '''Pattern Recognition''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (184, '''Pattern Recognition'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (185, '''Physical Removal''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (186, '''Physical Removal'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (187, '''Pick-up and Deliver''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (188, '''Pick-up and Deliver'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (189, '''Pieces as Map''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (190, '''Pieces as Map'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (191, '''Player Elimination''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (192, '''Player Elimination'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (193, '''Player Judge''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (194, '''Player Judge'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (195, '''Point to Point Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (196, '''Point to Point Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (197, '''Predictive Bid''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (198, '''Programmed Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (199, '''Programmed Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (200, '''Push Your Luck''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (201, '''Push Your Luck'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (202, '''Race''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (203, '''Race'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (204, '''Random Production''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (205, '''Random Production'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (206, '''Ratio / Combat Results Table''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (207, '''Ratio / Combat Results Table'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (208, '''Re-rolling and Locking''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (209, '''Re-rolling and Locking'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (210, '''Real-Time''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (211, '''Real-Time'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (212, '''Relative Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (213, '''Relative Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (214, '''Resource to Move''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (215, '''Resource to Move'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (216, '''Rock-Paper-Scissors''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (217, '''Rock-Paper-Scissors'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (218, '''Role Playing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (219, '''Role Playing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (220, '''Roles with Asymmetric Information''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (221, '''Roles with Asymmetric Information'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (222, '''Roll / Spin and Move''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (223, '''Roll / Spin and Move'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (224, '''Rondel''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (225, '''Rondel'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (226, '''Scenario / Mission / Campaign Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (227, '''Scenario / Mission / Campaign Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (228, '''Score-and-Reset Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (229, '''Score-and-Reset Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (230, '''Secret Unit Deployment''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (231, '''Secret Unit Deployment'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (232, '''Selection Order Bid''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (233, '''Selection Order Bid'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (234, '''Semi-Cooperative Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (235, '''Semi-Cooperative Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (236, '''Set Collection''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (237, '''Set Collection'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (238, '''Simulation''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (239, '''Simulation'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (240, '''Simultaneous Action Selection''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (241, '''Simultaneous Action Selection'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (242, '''Singing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (243, '''Singing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (244, '''Single Loser Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (245, '''Single Loser Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (246, '''Slide/Push''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (247, '''Slide/Push'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (248, '''Solo / Solitaire Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (249, '''Solo / Solitaire Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (250, '''Speed Matching''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (251, '''Speed Matching'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (252, '''Square Grid''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (253, '''Square Grid'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (254, '''Stacking and Balancing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (255, '''Stacking and Balancing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (256, '''Stat Check Resolution''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (257, '''Stat Check Resolution'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (258, '''Static Capture''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (259, '''Static Capture'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (260, '''Stock Holding''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (261, '''Stock Holding'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (262, '''Storytelling''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (263, '''Storytelling'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (264, '''Sudden Death Ending''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (265, '''Sudden Death Ending'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (266, '''Take That''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (267, '''Take That'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (268, '''Targeted Clues''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (269, '''Targeted Clues'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (270, '''Team-Based Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (271, '''Team-Based Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (272, '''Tech Trees / Tech Tracks''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (273, '''Tech Trees / Tech Tracks'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (274, '''Three Dimensional Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (275, '''Three Dimensional Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (276, '''Tile Placement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (277, '''Tile Placement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (278, '''Time Track''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (279, '''Time Track'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (280, '''Track Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (281, '''Track Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (282, '''Trading''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (283, '''Trading'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (284, '''Traitor Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (285, '''Traitor Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (286, '''Trick-taking''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (287, '''Trick-taking'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (288, '''Tug of War''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (289, '''Tug of War'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (290, '''Turn Order: Auction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (291, '''Turn Order: Auction'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (292, '''Turn Order: Claim Action''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (293, '''Turn Order: Claim Action'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (294, '''Turn Order: Pass Order''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (295, '''Turn Order: Pass Order'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (296, '''Turn Order: Progressive''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (297, '''Turn Order: Progressive'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (298, '''Turn Order: Random''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (299, '''Turn Order: Random'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (300, '''Turn Order: Role Order''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (301, '''Turn Order: Role Order'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (302, '''Turn Order: Stat-Based''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (303, '''Turn Order: Stat-Based'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (304, '''Variable Phase Order''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (305, '''Variable Phase Order'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (306, '''Variable Player Powers''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (307, '''Variable Player Powers'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (308, '''Variable Set-up''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (309, '''Variable Set-up'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (310, '''Victory Points as a Resource''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (311, '''Victory Points as a Resource'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (312, '''Voting''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (313, '''Voting'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (314, '''Worker Placement');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (315, '''Worker Placement with Dice Workers''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (316, '''Worker Placement with Dice Workers'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (317, '''Worker Placement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (318, '''Worker Placement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (319, '''Zone of Control'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (320, 'Bag');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (321, 'Different Worker Types''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (322, 'Different Worker Types'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (323, 'Inconnu');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (324, 'You Choose''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (325, 'You Choose'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (326, '["Prisoner''s Dilemma"');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (327, '[''Acting''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (328, '[''Acting'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (329, '[''Action Drafting''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (330, '[''Action Drafting'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (331, '[''Action Points''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (332, '[''Action Points'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (333, '[''Action Queue''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (334, '[''Action Queue'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (335, '[''Action Retrieval''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (336, '[''Action Timer''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (337, '[''Action Timer'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (338, '[''Action/Event''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (339, '[''Advantage Token''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (340, '[''Alliances''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (341, '[''Area Majority / Influence''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (342, '[''Area Majority / Influence'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (343, '[''Area Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (344, '[''Area Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (345, '[''Area-Impulse''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (346, '[''Area-Impulse'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (347, '[''Auction/Bidding''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (348, '[''Auction/Bidding'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (349, '[''Auction: Dexterity''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (350, '[''Auction: Dutch Priority''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (351, '[''Auction: Dutch''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (352, '[''Auction: Once Around'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (353, '[''Auction: Sealed Bid''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (354, '[''Auction: Turn Order Until Pass''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (355, '[''Automatic Resource Growth''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (356, '[''Betting and Bluffing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (357, '[''Betting and Bluffing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (358, '[''Bias''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (359, '[''Bingo''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (360, '[''Bribery''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (361, '[''Campaign / Battle Card Driven''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (362, '[''Campaign / Battle Card Driven'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (363, '[''Card Drafting''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (364, '[''Card Drafting'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (365, '[''Card Play Conflict Resolution''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (366, '[''Card Play Conflict Resolution'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (367, '[''Catch the Leader''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (368, '[''Chaining''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (369, '[''Chit-Pull System''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (370, '[''Chit-Pull System'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (371, '[''Closed Economy Auction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (372, '[''Command Cards''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (373, '[''Commodity Speculation''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (374, '[''Commodity Speculation'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (375, '[''Communication Limits''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (376, '[''Connections''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (377, '[''Connections'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (378, '[''Contracts''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (379, '[''Cooperative Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (380, '[''Cooperative Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (381, '[''Crayon Rail System''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (382, '[''Crayon Rail System'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (383, '[''Critical Hits and Failures''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (384, '[''Cube Tower''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (385, '[''Deck');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (386, '[''Deck Construction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (387, '[''Deck Construction'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (388, '[''Deduction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (389, '[''Deduction'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (390, '[''Dice Rolling''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (391, '[''Dice Rolling'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (392, '[''Die Icon Resolution''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (393, '[''Different Dice Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (394, '[''Drafting''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (395, '[''Drafting'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (396, '[''Elapsed Real Time Ending''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (397, '[''Enclosure''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (398, '[''Enclosure'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (399, '[''End Game Bonuses''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (400, '[''Events''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (401, '[''Finale Ending''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (402, '[''Flicking''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (403, '[''Flicking'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (404, '[''Follow''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (405, '[''Force Commitment'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (406, '[''Grid Coverage''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (407, '[''Grid Coverage'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (408, '[''Grid Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (409, '[''Grid Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (410, '[''Hand Management''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (411, '[''Hand Management'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (412, '[''Hexagon Grid''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (413, '[''Hexagon Grid'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (414, '[''Hidden Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (415, '[''Hidden Roles''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (416, '[''Hidden Victory Points''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (417, '[''Highest-Lowest Scoring''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (418, '[''Hot Potato''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (419, '[''Hot Potato'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (420, '[''I Cut');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (421, '[''Income''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (422, '[''Increase Value of Unchosen Resources''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (423, '[''Induction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (424, '[''Induction'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (425, '[''Investment''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (426, '[''King of the Hill'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (427, '[''Ladder Climbing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (428, '[''Ladder Climbing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (429, '[''Layering''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (430, '[''Legacy Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (431, '[''Line Drawing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (432, '[''Line Drawing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (433, '[''Line of Sight''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (434, '[''Line of Sight'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (435, '[''Loans''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (436, '[''Lose a Turn''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (437, '[''Mancala''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (438, '[''Mancala'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (439, '[''Map Addition''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (440, '[''Map Deformation''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (441, '[''Map Reduction''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (442, '[''Market''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (443, '[''Matching''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (444, '[''Measurement Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (445, '[''Melding and Splaying''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (446, '[''Memory''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (447, '[''Memory'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (448, '[''Modular Board''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (449, '[''Modular Board'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (450, '[''Move Through Deck''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (451, '[''Move Through Deck'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (452, '[''Movement Points'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (453, '[''Movement Template''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (454, '[''Moving Multiple Units'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (455, '[''Multiple Maps''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (456, '[''Narrative Choice / Paragraph''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (457, '[''Negotiation''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (458, '[''Network and Route Building''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (459, '[''Network and Route Building'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (460, '[''Once-Per-Game Abilities''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (461, '[''Ownership''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (462, '[''Paper-and-Pencil''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (463, '[''Paper-and-Pencil'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (464, '[''Passed Action Token''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (465, '[''Passed Action Token'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (466, '[''Pattern Building''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (467, '[''Pattern Building'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (468, '[''Pattern Recognition''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (469, '[''Pattern Recognition'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (470, '[''Physical Removal''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (471, '[''Physical Removal'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (472, '[''Pick-up and Deliver''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (473, '[''Pick-up and Deliver'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (474, '[''Pieces as Map''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (475, '[''Player Elimination''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (476, '[''Player Elimination'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (477, '[''Player Judge''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (478, '[''Player Judge'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (479, '[''Point to Point Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (480, '[''Point to Point Movement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (481, '[''Predictive Bid''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (482, '[''Push Your Luck''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (483, '[''Push Your Luck'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (484, '[''Race''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (485, '[''Race'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (486, '[''Re-rolling and Locking''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (487, '[''Real-Time''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (488, '[''Real-Time'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (489, '[''Relative Movement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (490, '[''Resource to Move'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (491, '[''Rock-Paper-Scissors''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (492, '[''Rock-Paper-Scissors'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (493, '[''Role Playing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (494, '[''Role Playing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (495, '[''Roles with Asymmetric Information''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (496, '[''Roles with Asymmetric Information'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (497, '[''Roll / Spin and Move''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (498, '[''Roll / Spin and Move'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (499, '[''Rondel''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (500, '[''Rondel'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (501, '[''Scenario / Mission / Campaign Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (502, '[''Score-and-Reset Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (503, '[''Score-and-Reset Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (504, '[''Secret Unit Deployment''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (505, '[''Secret Unit Deployment'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (506, '[''Semi-Cooperative Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (507, '[''Semi-Cooperative Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (508, '[''Set Collection''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (509, '[''Set Collection'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (510, '[''Simulation''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (511, '[''Simulation'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (512, '[''Simultaneous Action Selection''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (513, '[''Simultaneous Action Selection'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (514, '[''Singing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (515, '[''Singing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (516, '[''Single Loser Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (517, '[''Single Loser Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (518, '[''Slide/Push''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (519, '[''Slide/Push'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (520, '[''Solo / Solitaire Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (521, '[''Solo / Solitaire Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (522, '[''Square Grid''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (523, '[''Square Grid'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (524, '[''Stacking and Balancing''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (525, '[''Stacking and Balancing'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (526, '[''Stock Holding''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (527, '[''Stock Holding'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (528, '[''Storytelling''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (529, '[''Storytelling'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (530, '[''Take That''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (531, '[''Take That'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (532, '[''Targeted Clues'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (533, '[''Team-Based Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (534, '[''Team-Based Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (535, '[''Tile Placement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (536, '[''Tile Placement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (537, '[''Time Track'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (538, '[''Trading''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (539, '[''Trading'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (540, '[''Traitor Game''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (541, '[''Traitor Game'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (542, '[''Trick-taking''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (543, '[''Trick-taking'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (544, '[''Variable Phase Order''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (545, '[''Variable Phase Order'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (546, '[''Variable Player Powers''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (547, '[''Variable Player Powers'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (548, '[''Victory Points as a Resource'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (549, '[''Voting'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (550, '[''Worker Placement');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (551, '[''Worker Placement''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (552, '[''Worker Placement'']');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (553, 'and Pool Building''');
INSERT INTO MotCle (IDMotCle, NomMotCle) VALUES (554, 'and Pool Building'']');
